<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* This file handles pages, but only exists for the sake of child theme forward compatibility.

add_action( 'genesis_after_header', 'utility_pro_add_home_welcome' );
add_action( 'genesis_before_footer', 'utility_pro_add_call_to_action', 1 );
add_action( 'genesis_before_entry' , 'yoastbreadcrumps' );
add_action( 'genesis_before_header', 'genesis_do_nav' );

remove_action( 'genesis_site_title', 'genesis_seo_site_title' );
remove_action( 'genesis_site_description', 'genesis_seo_site_description' );
remove_action( 'genesis_site_description', 'genesis_seo_site_description' );

remove_action( 'genesis_before_loop', 'genesis_do_breadcrumbs' );
remove_action ('genesis_entry_content', 'featured_image' );
remove_action( 'genesis_after_header', 'genesis_do_nav' );
remove_action( 'genesis_site_description', 'genesis_seo_site_description' );

// Display content for the "Home Welcome" section
function utility_pro_add_home_welcome() {

	genesis_widget_area( 'utility-home-welcome',
		array(
			'before' => '<div class="home-welcome"><div class="wrap">',
			'after' => '</div></div>',
		)
	);
}

// Display content for the "Call to action" section
function utility_pro_add_call_to_action() {

	genesis_widget_area(
		'utility-call-to-action',
		array(
			'before' => '<div class="call-to-action-bar"><div class="wrap">',
			'after' => '</div></div>',
		)
	);
}

genesis();
